### ISSUE TITLE
How did you generate these flow charts?

### ISSUE THREAD

**Issue by rew1nter** [SwarzChen/shorturl-maker#1]
I find these absolutely amazing. What did you use to make it?
![image](https://github.com/DenChenn/shorturl-maker/assets/64508791/ff2daf10-35e7-477f-81a5-68b487616991)

**Comment by DenChenn** [comment]
I made them with this : [googlecloudcheatsheet](https://googlecloudcheatsheet.withgoogle.com/architecture)
: )

**Comment by rew1nter** [comment]
sweet
